### ISSUE TITLE
VM root password not documented

### ISSUE THREAD

**Issue by nickcounts** [nasa/CFS-101#1]
Unable to find the root password for the VM. 

If the devs don't want to add the root password to the documentation, perhaps they can configure the VM so the `dev` user is in the sudoer's list?

Including this info would make the VM a much more useful tool, as additional tools could be installed by the users

**Comment by nickcounts** [comment]
**Update for any other users:**

If the developers don't document the root password to the VM, you can reset it.

Since this is CentOS 6, the steps to reset the root user password are relatively straightforward. You need to reboot the VM into single user mode and use the `passwd` command to change the root password.

# Root Password Reset Steps

1. Reboot your VM (or start it up from a shutdown state)

2. You will see a GRUB boot prompt telling you to press any key - you have only a few seconds to press a key to stop the automated booting process. (If you miss this prompt you will need to restart the VM again)

3. At the GRUB prompt, type "a" to append to the boot command.

<img width="752" alt="grub-menu" src="https://user-images.githubusercontent.com/10506020/35353863-82ecac60-0116-11e8-9f9b-bf64c835776c.png">

4. Add the text  `single` to the end of the line (with a space) and press enter. It should look something like this:

<img width="752" alt="grub-prompt-with-single" src="https://user-images.githubusercontent.com/10506020/35353864-82f8a164-0116-11e8-89a3-1ab7e88619d2.png">

The system will boot and you will see the root prompt. 
5. Type `passwd` to change the root-password and then reboot again (use the `reboot` command or the VM controls)

<img width="832" alt="single-user-mode-psswd" src="https://user-images.githubusercontent.com/10506020/35353865-83093ca4-0116-11e8-8e8b-e2208f039f33.png">

**Comment by aFunnyBit** [comment]
Inside the guide:

```This training guide is used with a Virtual Machine (VM) called CentOS-6.8-CFS-101. Log in to the VM as "dev" user with password "cfs101!!".```

**Comment by nickcounts** [comment]
Respectfully, the issue is not the user password, but the _root_ password.

`dev` is not on the sudoers list, so there are many useful things that can't be done on the VM - installing new editors, using yum, changing most network settings, etc...

It would be very convenient to have the root password included in the documentation. But as I said in my earlier post, it is of course possible to reset it by booting into single user mode.

**Comment by tngo67** [comment]
Due to government IT policy, I am not allowed to share to root password or making "dev" user superuser.
This VM is restricted to be used for training purpose only.  You should not need to install any additional RPMs for this training.

**Comment by nickcounts** [comment]
Government policy restricts your documenting the root password to a _virtual machine_ ? As in, a non-real computer, not connected to any actual government hardware, made specifically to distribute a working version of this _open source_ and _publicly released_ technology?

I believe you, but I wonder if that's really the intent of those rules. In any case, I appreciate the response.

**Comment by nickcounts** [comment]
Perhaps it would be helpful to specify the terms of use with either a license file, or in the repository's readme. The only thing I see that's related is in the `oss-CFS-101.html` file, section 1.2 "Training Materials" paragraph 2 :

>The development environment for this VM has been setup & configured with the appropriate system libraries, open-source version of the CFS software, and project workspace for the training. As a new team member who just join an existing CFS-based project, it is reasonable to expect the project’s development environment and workspace to be setup-ready. But if a project just get started, then it is a one-time task to setup & configure the development environment and workspace to run CFS. This should be done by one person at the start of the project for everyone else in the team to use thereafter.

In the context of your comments, I can read the above as implying "not for development use," however "But if a project just get started, then it is a one-time task to setup & configure the development environment and workspace to run CFS" seems to indicate this product is intended as a getting started development environment.

**Comment by tngo67** [comment]
Good point, Nick.  I'll update that to clarify.  Thanks.

**Comment by tngo67** [comment]
Training guide has been updated to comment that root password will not be provided due to company's IT policy.

**Comment by NickHowes** [comment]
Which means it's impossible to update the VM guest additions without changing PW in CMDline

**Comment by tngo67** [comment]
Yes.  It is unfortunate.  I am looking at other means to provide the workspace in place of a VM, like a docker container, for example.  Unfortunately, docker doesn't seem to be very friendly on Windows.  If you run Docker on Windows, you cannot run other Virtual Machine.  Another approach is to have folks build their own VM & I provide instructions on installations of additional RPMs to run CFS.
