### ISSUE TITLE
Problem with sch.so

### ISSUE THREAD

**Issue by Hryurt** [nasa/CFS-101#11]
I followed the instructions until chapter 4.5. When I run the new flight system,  it could not load SCH. I checked every step 3 times. I found that there is no "so" file for sch in "home/dev/Training_workspace/CFS-101/build/exe/cpu1/cf ". What can be the problem? Could you please help me? 
Thank you

**Comment by tngo67** [comment]
Without knowing the context, I'm guessing SCH got omit from the build list.  Can you check step #2 of section 4.4 and make sure SCH is included in the TGT1_APPLIST?  If it is, then there must be some build errors relating to the SCH app.  Take a look at the build output when you execute "$ make".
