### ISSUE TITLE
gen_app_code tool

### ISSUE THREAD

**Issue by NickHauptvogel** [nasa/CFS-101#12]
Hi,

I recently worked through the tutorial and asked myself, where the gen_app_code tool for creating apps efficiently has gone? How can I create an app without copy/pasting an existing one and manually refactoring all the dependencies?

Regards,
Nick

**Comment by tngo67** [comment]
Hi Nick,

I'm assuming you're referring to what is currently out there on github/nasa.  gen_app_code is going thru the NASA's open source process so that we could host it on github/nasa as its own repositories.  So stay tune.  It's coming.

**Comment by mentoc3000** [comment]
Any news on this? Can we expect this tool to be released?
