### ISSUE TITLE
please either add dev to sudo group or set root password to same

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/CFS-101#13]
Using the VM image, I should have total control of the system. I was able to get root by mounting the disk in another VM but there's no reason to not just give dev full sudo.

**Comment by tngo67** [comment]
Hi Chris.  I totally agree with you.  However, it is the JSC IT regulation that I have to meet.  That being said, you are free to modify your own copy however you see fit to suit your need.

**Comment by CDKnightNASA** [comment]
Ok, what about having a script that, when the VM is first booted, asks for a new root password (or dev password if dev is given sudo?)
