### ISSUE TITLE
question ...

### ISSUE THREAD

**Issue by bgmarchand** [nasa/CFS-101#14]
First of all, thank you for drafting this documentation, and maintaining the virtual machine environment to go with it. This has been the most helpful resource I have found to date on cFS, so kudos!!! I noticed somewhere in the documentation it was formally noted that the root account password on the virtual machine is not published or released. I have no problems with that at all. However, I was wondering if it would be possible to update the GitHub repo with a revised virtual machine that has the "dev" user added to the sudoers list in a limited role. At least so the user can install the virtual box guest additions. Otherwise, the user can't go into full screen mode or, more importantly, change the display view resolution. It is so small by default, like 640x480, on the 001 VMDK image that it's very difficult to visualize all the windows as one steps through the tutorial. You MAYBE, depending on the example, have enough room to see one window at a time but most of the time they're cut off at the bottom.

**Comment by bgmarchand** [comment]
Never mind! You can get around it by going to System --> Preferences --> Display and setting the resolution to match your display. That worked just fine to do what I needed without having to install the guest additions 👍

**Comment by tngo67** [comment]
Hi.  I just want to thank you for your feedbacks.  It's very satisfying for me to learn that CFS-101 is useful to the end users.  :-) While I can't do anything about our IT security guidelines, I will keep in mind of your suggestion, and will see if there's a way to set up limited role to "dev" user to maintain the VM in the future.
